dependencies:
  - python=3.10
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - mkdocs
  - wget
  - openjdk=17
  - tabix
  - plink
  - plink2
  - pip:
    - hail

