name: imo
dependencies:
  - python=3.11
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - mkdocs
  - openjdk=11
  - htslib
  - pyspark
  - wget
  - protobuf
  - hdf5
  - gatk4
  - plink
  - plink2
  - pip:
    - hail

