name: imo
dependencies:
  - python=3.11
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - tensorflow
  - pymc3
  - keras
  - pyvcf
  - pysam
  - biopython
  - mkdocs
  - openjdk=17
  - htslib
  - pyspark
  - wget
  - protobuf
  - hdf5
  - bedtools
  - samtools
  - bcftools
  - tabix
  - gatk4
  - plink
  - plink2
  - pip:
    - hail

